complete -c apt-gen-list -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "set-branch" -d 'Set APT repository branch (e.g., stable)'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "set-mirror" -d 'Set APT repository mirror'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "add-mirror" -d 'Add additional APT repository mirror'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "remove-mirror" -d 'Remove APT repository mirror'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "status" -d 'Show apt-gen-list status'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "add-component" -d 'Set APT repository component'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "remove-component" -d 'Remove APT repository component'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "add-custom-mirror" -d 'Add custom repository mirror'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "remove-custom-mirror" -d 'Remove custom repository mirror'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "speedtest" -d 'Run speed-test on available mirrors'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "list-mirrors" -d 'Show available mirror list'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "set-fastest-mirror-as-default" -d 'Set fastest mirror as default'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "reset-mirror" -d 'Reset mirror to default'
complete -c apt-gen-list -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c apt-gen-list -n "__fish_seen_subcommand_from set-branch" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from set-branch" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from set-mirror" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from set-mirror" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from add-mirror" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from add-mirror" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from remove-mirror" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from remove-mirror" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from status" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from status" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from add-component" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from add-component" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from remove-component" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from remove-component" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from add-custom-mirror" -s s -l also-set-mirror -d 'also set mirror as default'
complete -c apt-gen-list -n "__fish_seen_subcommand_from add-custom-mirror" -s a -l also-add-mirror -d 'also add mirror to list'
complete -c apt-gen-list -n "__fish_seen_subcommand_from add-custom-mirror" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from add-custom-mirror" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from remove-custom-mirror" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from remove-custom-mirror" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from speedtest" -s p -l parallel -d 'Test mirror performance concurrently, test will take a shorter amount of time, but results will only serve as a rough estimate and could vary between runs'
complete -c apt-gen-list -n "__fish_seen_subcommand_from speedtest" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from speedtest" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from list-mirrors" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from list-mirrors" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from set-fastest-mirror-as-default" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from set-fastest-mirror-as-default" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from reset-mirror" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from reset-mirror" -s V -l version -d 'Prints version information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c apt-gen-list -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
