# lists

# messages
disable-comp = Disabling component {$comp} ...
set-mirror = Setting {$mirror} as the default mirror!
remove-mirror = Removing {$mirror} from sources.list ...
write-sources = Writing /etc/apt/sources.list ...
run-refresh = Refreshing local mirror metadata ... 
activating-count-mirrors = Activating {$count} mirrors ...
select-open-or-close-mirrors = Select to enable or disable mirror(s) ...
help-message = Press [Space]/[Enter] to toggle selection, [Esc] to apply changes, [Ctrl-c] to abort.

# error messages
comp-not-found = The specified component {$comp} does not exist.
comp-already-enabled = The specified component {$comp} is already enabled.
branch-not-found = The specified branch is undefined or does not exist!
branch-already-enabled = The specified branch {$branch} is already enabled.
mirror-not-found = Cannot find mirror: {$mirror}. Please use `oma mirror' or `mirrormgr' to select a mirror from the list of available mirrors, or use `oma mirror custom-mirror' to add a custom mirror.
mirror-already-enabled = The specified mirror {$mirror} is already enabled!
mirror-already-disabled = The specified mirror {$mirror} is already disabled or does not exist！
mirror-error = Failed to fetch test data from {$mirror}, please check your network connection!
no-delete-only-mirror = You only have one mirror left, refusing to remove.
no-delete-only-comp = Refusing to remove essential component "main".
execute-pkexec-fail = Failed to execute `pkexec': {$e}.

# file content
generated = # Generated by mirrormgr. DO NOT EDIT THIS FILE!
